### ISSUE TITLE
I tried looking for "transformAssetUrls" in Vue Loader, but can't fine it

### ISSUE THREAD

**Issue by KaitoXion** [subotkevic/vue-lazy-image-loading#3]
Vue Loader - Asset URL Handling
I tried looking for "transformAssetUrls" in Vue Loader, but can't fine it.

would you be so kind to give the full directory of it?

**Comment by subotkevic** [comment]
You should add that yourself in your webpack configuration file.

**Comment by KaitoXion** [comment]
thx for the reply.
although am new to this, and have no idea how to do that right now. I'll do my best to look into it.

Searching through google didn't give me a clear idea or how to do it. So I guess what's left is to read the code and try to understand it... 

thank you.
